java_binary(
    name = "ThreadedServer",
    srcs = glob(["src/ThreadedServer.java", "src/Handler.java", "src/Utils.java"]),
    main_class = "ThreadedServer",
)

java_binary(
    name = "Client",
    srcs = glob(["src/Client.java", "src/Utils.java"]),
    main_class = "Client",
)
